/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package darka;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel_duessmann
 */
public class TelaHistoria5 extends javax.swing.JFrame {

    /**
     * Creates new form TelaHistoria5
     */
    public TelaHistoria5() {
        initComponents();
        PerfilUsuario.checkpoint = 5;
        if (ArmazenaCadastroPersonagem.sexo == null) {
            ArmazenaCadastroPersonagem.sexo = "Masculino";
        }
        if (ArmazenaCadastroPersonagem.sexo.equals("Masculino")) {
            txtHistoria.setText("<html>Ambos então vão dormir. <br>Ao amanhecer Meskim entrega uma espada e 3 poções de cura para "+ArmazenaCadastroPersonagem.nome+". Assim não ficando despreparado para uma possível batalha.<br>Clique nos itens para pegá-los.</html>");
        } else {
            txtHistoria.setText("<html>Ambos então vão dormir. <br>Ao amanhecer Meskim entrega uma espada e 3 poções de cura para "+ArmazenaCadastroPersonagem.nome+". Assim não ficando despreparada para uma possível batalha.<br>Clique nos itens para pegá-los</html>");
        }
        
        btnInventario.setOpaque(false);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setBorderPainted(false);
        
        btnInventario.setOpaque(false);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setBorderPainted(false);
        imgPot1.setOpaque(false);
        imgPot1.setContentAreaFilled(false);
        imgPot1.setBorderPainted(false);
        imgPot2.setOpaque(false);
        imgPot2.setContentAreaFilled(false);
        imgPot2.setBorderPainted(false);
        imgPot3.setOpaque(false);
        imgPot3.setContentAreaFilled(false);
        imgPot3.setBorderPainted(false);
        imgEspada.setOpaque(false);
        imgEspada.setContentAreaFilled(false);
        imgEspada.setBorderPainted(false);
        
        if (PerfilUsuario.pot1 == true) {
            imgPot1.setVisible(true);
        } else {
            imgPot1.setVisible(false);
        }
        
        if (PerfilUsuario.pot2 == true) {
            imgPot2.setVisible(true);
        } else {
            imgPot2.setVisible(false);
        }
        
        if (PerfilUsuario.pot3 == true) {
            imgPot3.setVisible(true);
        } else {
            imgPot3.setVisible(false);
        }
        
        if (PerfilUsuario.espada == true) {
            imgEspada.setVisible(true);
        } else {
            imgEspada.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHistoria = new javax.swing.JLabel();
        botao1 = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        imgEspada = new javax.swing.JButton();
        imgPot3 = new javax.swing.JButton();
        imgPot1 = new javax.swing.JButton();
        imgPot2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHistoria.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtHistoria.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 1050, 140));

        botao1.setBackground(new java.awt.Color(255, 255, 255));
        botao1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        botao1.setText("Continuar o caminho");
        botao1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });
        getContentPane().add(botao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 260, -1));

        btnInventario.setBackground(new java.awt.Color(51, 51, 51));
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backpack.png"))); // NOI18N
        btnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 450, 180, 180));

        imgEspada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sword.png"))); // NOI18N
        imgEspada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgEspada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgEspadaActionPerformed(evt);
            }
        });
        getContentPane().add(imgEspada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 279, 280, 270));

        imgPot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/potion1.png"))); // NOI18N
        imgPot3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgPot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgPot3ActionPerformed(evt);
            }
        });
        getContentPane().add(imgPot3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, -1, -1));

        imgPot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/potion1.png"))); // NOI18N
        imgPot1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgPot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgPot1ActionPerformed(evt);
            }
        });
        getContentPane().add(imgPot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        imgPot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/potion1.png"))); // NOI18N
        imgPot2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgPot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgPot2ActionPerformed(evt);
            }
        });
        getContentPane().add(imgPot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        if (PerfilUsuario.espada == false) {
        TelaHistoria6 telaHistoria6 = new TelaHistoria6();
        telaHistoria6.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
        telaHistoria6.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você deve pegar a espada para continuar.");
        }
    }//GEN-LAST:event_botao1ActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        TelaInventario telaInventario = new TelaInventario();
        telaInventario.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
        telaInventario.setVisible(true);
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void imgEspadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgEspadaActionPerformed
        imgEspada.setVisible(false);
        PerfilUsuario.espada = false;
        PerfilUsuario.dano = 150;
    }//GEN-LAST:event_imgEspadaActionPerformed

    private void imgPot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgPot1ActionPerformed
        imgPot1.setVisible(false);
        PerfilUsuario.qtdePot ++;
        PerfilUsuario.pot1 = false;
    }//GEN-LAST:event_imgPot1ActionPerformed

    private void imgPot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgPot2ActionPerformed
        imgPot2.setVisible(false);
        PerfilUsuario.qtdePot ++;
        PerfilUsuario.pot2 = false;
    }//GEN-LAST:event_imgPot2ActionPerformed

    private void imgPot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgPot3ActionPerformed
        imgPot3.setVisible(false);
        PerfilUsuario.qtdePot ++;
        PerfilUsuario.pot3 = false;
    }//GEN-LAST:event_imgPot3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHistoria5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHistoria5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHistoria5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHistoria5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHistoria5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao1;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton imgEspada;
    private javax.swing.JButton imgPot1;
    private javax.swing.JButton imgPot2;
    private javax.swing.JButton imgPot3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtHistoria;
    // End of variables declaration//GEN-END:variables
}
