/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package darka;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel_duessmann
 */
public class TelaBatalha2 extends javax.swing.JFrame {

    /**
     * Creates new form TelaBatalha2
     */
    public TelaBatalha2() {
        initComponents();
        /*LUTA BOSS CONHECIMENTO*/
        if (ArmazenaCadastroPersonagem.sexo == null) {
            ArmazenaCadastroPersonagem.sexo = "Masculino";
        }
        if (ArmazenaCadastroPersonagem.sexo.equals("Masculino")){
            img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wise boss fight male.png")));
        } else {
            img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wise boss fight female.png")));
        }
        txtTexto.setText("É feito para andar e não anda.");
        txtVidaPersonagem.setText(Integer.toString(PerfilUsuario.vida));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVidaInimigo = new javax.swing.JLabel();
        txtVidaPersonagem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTexto = new javax.swing.JLabel();
        btnTalher = new javax.swing.JButton();
        btnRua = new javax.swing.JButton();
        btnBuraco = new javax.swing.JButton();
        btnRelogio = new javax.swing.JButton();
        btnPneu = new javax.swing.JButton();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtVidaInimigo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        txtVidaInimigo.setForeground(new java.awt.Color(204, 0, 0));
        txtVidaInimigo.setText("1000");
        getContentPane().add(txtVidaInimigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, -1, -1));

        txtVidaPersonagem.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        txtVidaPersonagem.setForeground(new java.awt.Color(0, 153, 51));
        txtVidaPersonagem.setText("vida");
        getContentPane().add(txtVidaPersonagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("O que é, o que é?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        txtTexto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTexto.setForeground(new java.awt.Color(255, 255, 255));
        txtTexto.setText("É feito para andar e não anda.");
        getContentPane().add(txtTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        btnTalher.setBackground(new java.awt.Color(255, 255, 255));
        btnTalher.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnTalher.setText("Talher");
        btnTalher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTalher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTalherActionPerformed(evt);
            }
        });
        getContentPane().add(btnTalher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 620, 160, -1));

        btnRua.setBackground(new java.awt.Color(255, 255, 255));
        btnRua.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnRua.setText("Rua");
        btnRua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, 160, -1));

        btnBuraco.setBackground(new java.awt.Color(255, 255, 255));
        btnBuraco.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnBuraco.setText("Buraco");
        btnBuraco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuraco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuracoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuraco, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 160, -1));

        btnRelogio.setBackground(new java.awt.Color(255, 255, 255));
        btnRelogio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnRelogio.setText("Relógio");
        btnRelogio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelogio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelogioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelogio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 160, -1));

        btnPneu.setBackground(new java.awt.Color(255, 255, 255));
        btnPneu.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnPneu.setText("Pneu");
        btnPneu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPneu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPneuActionPerformed(evt);
            }
        });
        getContentPane().add(btnPneu, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, 160, -1));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wise boss fight male.png"))); // NOI18N
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTalherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTalherActionPerformed
        String texto = txtTexto.getText();
        if (texto.equals("Não se come, mas é bom para se comer.")) {
            txtTexto.setText("Quanto mais ruga tem, mais novo é.");
            btnTalher.setVisible(false);
        } else {
                        
            Object[] options = { "Fechar o jogo", "Voltar ao ínicio"};
            int opcao = JOptionPane.showOptionDialog(null, ArmazenaCadastroPersonagem.nome+" errou a resposta e o inimigo "
                    + "o mata.", "Morte", 
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
            if (opcao == 1){
                VoltarAoInicio.reinicia();
                TelaHistoria1 telaHistoria1 = new TelaHistoria1();
                telaHistoria1.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dispose();
                telaHistoria1.setVisible(true);
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btnTalherActionPerformed

    private void btnRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuaActionPerformed

            txtTexto.setText("Dá muitas voltas e não sai do lugar.");
            btnRua.setVisible(false);
  

    }//GEN-LAST:event_btnRuaActionPerformed

    private void btnBuracoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuracoActionPerformed
        String texto = txtTexto.getText();
        if (texto.equals("Quando mais se tira, mais aumenta.")) {
            btnBuraco.setVisible(false);
            
            PerfilUsuario.vida = 550;
            PerfilUsuario.vida += 250;
            TelaPosBatalha2_3_4 telaPosBatalha2_3_4 = new TelaPosBatalha2_3_4();
            telaPosBatalha2_3_4.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaPosBatalha2_3_4.setVisible(true);
            

        } else {
            
            Object[] options = { "Fechar o jogo", "Voltar ao ínicio"};
            int opcao = JOptionPane.showOptionDialog(null, ArmazenaCadastroPersonagem.nome+" errou a resposta e o inimigo "
                    + "o mata.", "Morte", 
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
            if (opcao == 1){
                VoltarAoInicio.reinicia();
                TelaHistoria1 telaHistoria1 = new TelaHistoria1();
                telaHistoria1.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dispose();
                telaHistoria1.setVisible(true);
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btnBuracoActionPerformed

    private void btnRelogioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelogioActionPerformed
        String texto = txtTexto.getText();
        if (texto.equals("Dá muitas voltas e não sai do lugar.")) {
            txtTexto.setText("Não se come, mas é bom para se comer.");
            btnRelogio.setVisible(false);
        } else {
                        
            Object[] options = { "Fechar o jogo", "Voltar ao ínicio"};
            int opcao = JOptionPane.showOptionDialog(null, ArmazenaCadastroPersonagem.nome+" errou a resposta e o inimigo "
                    + "o mata.", "Morte", 
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
            if (opcao == 1){
                VoltarAoInicio.reinicia();
                TelaHistoria1 telaHistoria1 = new TelaHistoria1();
                telaHistoria1.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dispose();
                telaHistoria1.setVisible(true);
            } else {
                System.exit(0);
            }
        }

    }//GEN-LAST:event_btnRelogioActionPerformed

    private void btnPneuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPneuActionPerformed
        String texto = txtTexto.getText();
        if (texto.equals("Quanto mais ruga tem, mais novo é.")) {
            txtTexto.setText("Quando mais se tira, mais aumenta.");
            btnPneu.setVisible(false);
        } else {
                        
            Object[] options = { "Fechar o jogo", "Voltar ao ínicio"};
            int opcao = JOptionPane.showOptionDialog(null, ArmazenaCadastroPersonagem.nome+" errou a resposta e o inimigo "
                    + "o mata.", "Morte", 
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
            if (opcao == 1){
                VoltarAoInicio.reinicia();
                TelaHistoria1 telaHistoria1 = new TelaHistoria1();
                telaHistoria1.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dispose();
                telaHistoria1.setVisible(true);
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btnPneuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBatalha2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuraco;
    private javax.swing.JButton btnPneu;
    private javax.swing.JButton btnRelogio;
    private javax.swing.JButton btnRua;
    private javax.swing.JButton btnTalher;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtTexto;
    private javax.swing.JLabel txtVidaInimigo;
    private javax.swing.JLabel txtVidaPersonagem;
    // End of variables declaration//GEN-END:variables
}
