/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package darka;

import javax.swing.JFrame;

/**
 *
 * @author gabriel_duessmann
 */
public class TelaInventario extends javax.swing.JFrame {

    /**
     * Creates new form TelaInventario
     */
    public TelaInventario() {
        initComponents();
        if (PerfilUsuario.qtdePot == 0) {
            imgPot.setVisible(false);   
            txtQtdPot.setVisible(false);
        } else {
            txtQtdPot. setText(Integer.toString(PerfilUsuario.qtdePot));
        }

        if (PerfilUsuario.qtdeBomba == 0) {
            imgBomba.setVisible(false);
            txtQtdBomba.setVisible(false);
        } else {
            txtQtdBomba. setText(Integer.toString(PerfilUsuario.qtdeBomba));
        }
        
        if (ArmazenaCadastroPersonagem.sexo == null) {
            ArmazenaCadastroPersonagem.sexo = "Masculin0";
        }
        if (ArmazenaCadastroPersonagem.sexo.equals("Masculino")) {
            imgPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/male2.png")));
        
        } else {
            imgPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/female2.png")));
        }
        
        btnVoltar.setOpaque(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setBorderPainted(false);
        
        txtDano.setText(Integer.toString(PerfilUsuario.dano));
        txtVida.setText(Integer.toString(PerfilUsuario.vida));
        txtDefesa.setText(Integer.toString(PerfilUsuario.defesa));
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        imgBomba = new javax.swing.JLabel();
        imgPot = new javax.swing.JLabel();
        txtDano = new javax.swing.JLabel();
        txtQtdBomba = new javax.swing.JLabel();
        txtQtdPot = new javax.swing.JLabel();
        txtDefesa = new javax.swing.JLabel();
        txtVida = new javax.swing.JLabel();
        imgPersonagem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setBackground(new java.awt.Color(0, 0, 0));
        btnVoltar.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 630, 240, 60));

        imgBomba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bomb2.png"))); // NOI18N
        getContentPane().add(imgBomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, 240));

        imgPot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/potion2.png"))); // NOI18N
        getContentPane().add(imgPot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 260));

        txtDano.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtDano.setForeground(new java.awt.Color(255, 255, 255));
        txtDano.setText("150");
        getContentPane().add(txtDano, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 480, -1, -1));

        txtQtdBomba.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtQtdBomba.setForeground(new java.awt.Color(255, 255, 255));
        txtQtdBomba.setText("0");
        getContentPane().add(txtQtdBomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 30, -1));

        txtQtdPot.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtQtdPot.setForeground(new java.awt.Color(255, 255, 255));
        txtQtdPot.setText("0");
        getContentPane().add(txtQtdPot, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 30, -1));

        txtDefesa.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtDefesa.setForeground(new java.awt.Color(255, 255, 255));
        txtDefesa.setText("0");
        getContentPane().add(txtDefesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 480, -1, -1));

        txtVida.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtVida.setForeground(new java.awt.Color(255, 255, 255));
        txtVida.setText("550");
        getContentPane().add(txtVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 480, -1, -1));

        imgPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/male2.png"))); // NOI18N
        getContentPane().add(imgPersonagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, 330, 370));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/inventory.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        if (PerfilUsuario.checkpoint == 1) {
            TelaHistoria1 telaHistoria1 = new TelaHistoria1();
            telaHistoria1.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria1.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 2) {
            TelaHistoria2 telaHistoria2 = new TelaHistoria2();
            telaHistoria2.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria2.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 3) {
            TelaHistoria3 telaHistoria3 = new TelaHistoria3();
            telaHistoria3.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria3.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 4) {
            TelaHistoria4 telaHistoria4 = new TelaHistoria4();
            telaHistoria4.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria4.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 5) {
            TelaHistoria5 telaHistoria5 = new TelaHistoria5();
            telaHistoria5.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria5.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 6) {
            TelaHistoria6 telaHistoria6 = new TelaHistoria6();
            telaHistoria6.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria6.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 7) {
            TelaHistoria7 telaHistoria7 = new TelaHistoria7();
            telaHistoria7.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria7.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 8) {
            TelaHistoria8 telaHistoria8 = new TelaHistoria8();
            telaHistoria8.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria8.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 9) {
            TelaHistoria9 telaHistoria9 = new TelaHistoria9();
            telaHistoria9.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria9.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 10) {
            TelaHistoria10 telaHistoria10 = new TelaHistoria10();
            telaHistoria10.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria10.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 11) {
            TelaHistoria11 telaHistoria11 = new TelaHistoria11();
            telaHistoria11.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria11.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 12) {
            TelaHistoria12 telaHistoria12 = new TelaHistoria12();
            telaHistoria12.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria12.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 13) {
            TelaHistoria13 telaHistoria13 = new TelaHistoria13();
            telaHistoria13.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria13.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 14) {
            TelaHistoria14 telaHistoria14 = new TelaHistoria14();
            telaHistoria14.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria14.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 15) {
            TelaHistoria15 telaHistoria15 = new TelaHistoria15();
            telaHistoria15.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria15.setVisible(true);
        } else if (PerfilUsuario.checkpoint == 16) {
            TelaHistoria16 telaHistoria16 = new TelaHistoria16();
            telaHistoria16.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria16.setVisible(true);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel imgBomba;
    private javax.swing.JLabel imgPersonagem;
    private javax.swing.JLabel imgPot;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtDano;
    private javax.swing.JLabel txtDefesa;
    private javax.swing.JLabel txtQtdBomba;
    private javax.swing.JLabel txtQtdPot;
    private javax.swing.JLabel txtVida;
    // End of variables declaration//GEN-END:variables
}
