/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package darka;

import javax.swing.JFrame;

/**
 *
 * @author gabriel_duessmann
 */
public class TelaCadastroPersonagem extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroPersonagem
     */
    public TelaCadastroPersonagem() {
        initComponents();
        imgMasc.setVisible(false);
        imgFem.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdGrupo = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNomePersonagem = new javax.swing.JTextField();
        rdMasc = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rdFem = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        imgFem = new javax.swing.JLabel();
        imgMasc = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton2.setText("Criar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 90, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome do personagem:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        txtNomePersonagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomePersonagem.setToolTipText("Digite o nome do seu personagem");
        txtNomePersonagem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtNomePersonagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 240, 30));

        rdMasc.setBackground(new java.awt.Color(0, 0, 0));
        rdGrupo.add(rdMasc);
        rdMasc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdMasc.setForeground(new java.awt.Color(255, 255, 255));
        rdMasc.setText("Masculino");
        rdMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMascActionPerformed(evt);
            }
        });
        getContentPane().add(rdMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton3.setText("Limpar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, 90, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 44)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CRIAÇÃO DE PERSONAGEM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        rdFem.setBackground(new java.awt.Color(0, 0, 0));
        rdGrupo.add(rdFem);
        rdFem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdFem.setForeground(new java.awt.Color(255, 255, 255));
        rdFem.setText("Feminino");
        rdFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFemActionPerformed(evt);
            }
        });
        getContentPane().add(rdFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sexo:");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        imgFem.setForeground(new java.awt.Color(255, 255, 255));
        imgFem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/female1.png"))); // NOI18N
        getContentPane().add(imgFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 180, -1));

        imgMasc.setForeground(new java.awt.Color(255, 255, 255));
        imgMasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/male1.png"))); // NOI18N
        getContentPane().add(imgMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 170, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jButton4.setText("Voltar ao Menu");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dragon character registration.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nome = txtNomePersonagem.getText();
        String sexo;
        if (rdMasc.isSelected()) {
            sexo = "Masculino";
        } else if (rdFem.isSelected()){
            sexo = "Feminino";
        } else {
            sexo = "";
        }
        boolean verificador = FazCadastroELogin.cadastraPersonagem(nome, sexo);
        if (verificador == false) {
            TelaCadastroPersonagem telaCadastroPersonagem = new TelaCadastroPersonagem();
            telaCadastroPersonagem.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaCadastroPersonagem.setVisible(true);
        } else {
            TelaHistoria1 telaHistoria1 = new TelaHistoria1();
            telaHistoria1.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria1.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtNomePersonagem.setText("");
        rdGrupo.clearSelection();
        imgMasc.setVisible(false);
        imgFem.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rdFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFemActionPerformed
        imgFem.setVisible(true);
        imgMasc.setVisible(false);
    }//GEN-LAST:event_rdFemActionPerformed

    private void rdMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMascActionPerformed
        imgMasc.setVisible(true);
        imgFem.setVisible(false);
    }//GEN-LAST:event_rdMascActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TelaMenu telaMenu = new TelaMenu();
        telaMenu.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
        telaMenu.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroPersonagem telaCadastroPersonagem = new TelaCadastroPersonagem(); 
                telaCadastroPersonagem.setExtendedState(JFrame.MAXIMIZED_BOTH);
                telaCadastroPersonagem.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFem;
    private javax.swing.JLabel imgMasc;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton rdFem;
    private javax.swing.ButtonGroup rdGrupo;
    private javax.swing.JRadioButton rdMasc;
    private javax.swing.JTextField txtNomePersonagem;
    // End of variables declaration//GEN-END:variables
}
