/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package darka;

import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel_duessmann
 */
public class TelaHistoria1 extends javax.swing.JFrame {

    /**
     * Creates new form TelaHistoria1
     */
    public TelaHistoria1() {
        initComponents();
        PerfilUsuario.checkpoint = 1;
        if (ArmazenaCadastroPersonagem.sexo == null) {
            ArmazenaCadastroPersonagem.sexo = "Masculino";
        }
        if (ArmazenaCadastroPersonagem.sexo.equals("Masculino")) {
            txtHistoria.setText("<html>O herói acorda com a voz de sua mãe o chamando, vai até a sala onde ela está " +
            "e o manda ir até a feira. " +
            "Então vai até a feira comprar os produtos e alimentos e volta para a casa.<br>" +
            "Quando está voltando para casa, próximo ao vilarejo, vê a casa de todos os moradores em chamas. Preocupado com sua" +
            " mãe, sai correndo para tentar salvá-la.<br>"+
            "Quando abre a porta da casa, percebe um vulto sobre as paredes.</html>");
        } else {
            txtHistoria.setText("<html>A heroína acorda com a voz de sua mãe a chamando, vai até a sala onde ela está " +
            "e a manda ir até a feira. " +
            "Então vai até a feira comprar os produtos e alimentos e volta para a casa.<br>" +
            "Quando está voltando para casa, próximo ao vilarejo, vê a casa de todos os moradores em chamas. Preocupada com sua" +
            " mãe, sai correndo para tentar salvá-la.<br>"+
            "Quando abre a porta da casa, percebe um vulto sobre as paredes.</html>");
        }
        
        btnInventario.setOpaque(false);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHistoria = new javax.swing.JLabel();
        botao1 = new javax.swing.JButton();
        botao2 = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHistoria.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtHistoria.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 1050, 230));

        botao1.setBackground(new java.awt.Color(255, 255, 255));
        botao1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        botao1.setText("Ir atrás do vulto");
        botao1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });
        getContentPane().add(botao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 300, -1));

        botao2.setBackground(new java.awt.Color(255, 255, 255));
        botao2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        botao2.setText("Tentar salvar sua mãe");
        botao2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao2ActionPerformed(evt);
            }
        });
        getContentPane().add(botao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 300, -1));

        btnInventario.setBackground(new java.awt.Color(51, 51, 51));
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backpack.png"))); // NOI18N
        btnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 450, 180, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        Object[] options = { "Fechar o jogo", "Voltar ao ínicio"};
        int opcao = JOptionPane.showOptionDialog(null, ArmazenaCadastroPersonagem.nome+" corre atrás do vulto, porém ele "
                + "pula por um penhasco e você não \nconsegue pular, cai sobre todo penhasco e morre no fim da queda.", "Morte", 
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        if (opcao == 1){
            VoltarAoInicio.reinicia();
            TelaHistoria1 telaHistoria1 = new TelaHistoria1();
            telaHistoria1.setExtendedState(JFrame.MAXIMIZED_BOTH);
            dispose();
            telaHistoria1.setVisible(true);
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_botao1ActionPerformed

    private void botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao2ActionPerformed
        TelaHistoria2 telaHistoria2 = new TelaHistoria2();
        telaHistoria2.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
        telaHistoria2.setVisible(true);
    }//GEN-LAST:event_botao2ActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        TelaInventario telaInventario = new TelaInventario();
        telaInventario.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
        telaInventario.setVisible(true);              
    }//GEN-LAST:event_btnInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHistoria1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHistoria1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHistoria1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHistoria1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHistoria1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton btnInventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtHistoria;
    // End of variables declaration//GEN-END:variables
}
