 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package darka;

import javax.swing.JFrame;

/**
 *
 * @author gabriel_duessmann
 */
public class TelaHistoria3 extends javax.swing.JFrame {

    /**
     * Creates new form TelaHistoria3
     */
    public TelaHistoria3() {
        initComponents();
        PerfilUsuario.checkpoint = 3;
        if (ArmazenaCadastroPersonagem.sexo == null) {
            ArmazenaCadastroPersonagem.sexo = "Masculino";
        }
        if (ArmazenaCadastroPersonagem.sexo.equals("Masculino")) {
            txtHistoria.setText("<html>-"+ArmazenaCadastroPersonagem.nome+": SAI DE PERTO DE MIM.<br>" +
            "-Meskim: Calma! Você está com fome?  <br>" +
            "-"+ArmazenaCadastroPersonagem.nome+": Você não vai me machucar?<br>" +
            "-Meskim: Eu, te machucar, HAHAHAHA. Eu te salvei, porque eu iria querer te machucar?<br>" +
            "-"+ArmazenaCadastroPersonagem.nome+": Ah, obrigado por ter me salvado, mas eu não te conheço, qual é o seu nome?<br>" +
            "-Meskim: Oh, mais é claro! Que falta de educação da minha parte, meu nome é Meskim.<br>" +
            "-"+ArmazenaCadastroPersonagem.nome+": O que aconteceu comigo?<br>" +
            "-Meskim: Te encontrei desmaiado então eu te trouxe para minha casa.<br>" +
            "-"+ArmazenaCadastroPersonagem.nome+": Você viu o que aconteceu com meu vilarejo? E… CADE MINHA MÃE???<br>" +
            "-Meskim: Claro que vi, eu estava indo atrás de quem fez isso, mas eu o perdi de vista, então fui até a vila ver se tinha alguém ferido e se precisavam de ajuda. E a única pessoa na qual ainda estava respirando era você, mais ninguém!<br>" +
            "-"+ArmazenaCadastroPersonagem.nome+": Nãoooo, não pode ser, minha mãe. ME FALE O NOME DE QUEM FEZ ISSO, ELE ME PAGA!<br>" +
            "-Meskim: O nome dele é Zabba!<br>" +
            "-"+ArmazenaCadastroPersonagem.nome+": E você sabe onde está esse tal de Zabba?<br>" +
            "-Meskim: Sei, vamos iniciar nossa jornada !</html>");
        } else {
            txtHistoria.setText("<html>-"+ArmazenaCadastroPersonagem.nome+" : SAI DE PERTO DE MIM.<br>" +
            "-Meskim: Calma! Você está com fome?  <br>" +
            "-"+ArmazenaCadastroPersonagem.nome+": Você não vai me machucar?<br>" +
            "-Meskim: Eu, te machucar, HAHAHAHA, eu te salvei, porque eu iria querer te machucar?<br>" +
            "-"+ArmazenaCadastroPersonagem.nome+": Ah, obrigada por ter me salvado, mas eu não te conheço, qual é o seu nome?<br>" +
            "-Meskim: Oh, mais é claro, que falta de educação da minha parte, meu nome é Meskim.<br>" +
            "-"+ArmazenaCadastroPersonagem.nome+": O que aconteceu comigo?<br>" +
            "-Meskim: Te encontrei desmaiada então eu te trouxe para minha casa.<br>" +
            "-"+ArmazenaCadastroPersonagem.nome+": Você viu o que aconteceu com meu vilarejo?E… CADE MINHA MÃE???<br>" +
            "-Meskim: Claro que vi, eu estava indo atrás de quem fez isso, mas eu o perdi de vista, então fui até a vila ver se tinha alguém ferido e se precisavam de ajuda. E a única pessoa na qual ainda estava respirando era você, mais ninguém!<br>" +
            "-"+ArmazenaCadastroPersonagem.nome+": Nãoooo, não pode ser, minha mãe. ME FALE O NOME DE QUEM FEZ ISSO, ELE ME PAGA!<br>" +
            "-Meskim: O nome dele é Zabba!<br>" +
            "-"+ArmazenaCadastroPersonagem.nome+": E você sabe onde está esse tal de Zabba?<br>" +
            "-Meskim: Sei, vamos iniciar nossa jornada !</html>");    
        }
        btnInventario.setOpaque(false);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHistoria = new javax.swing.JLabel();
        botao1 = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHistoria.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        txtHistoria.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 1090, 480));

        botao1.setBackground(new java.awt.Color(255, 255, 255));
        botao1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        botao1.setText("Iniciar jornada");
        botao1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });
        getContentPane().add(botao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 230, -1));

        btnInventario.setBackground(new java.awt.Color(51, 51, 51));
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backpack.png"))); // NOI18N
        btnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 450, 180, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
     
        TelaHistoria4 telaHistoria4 = new TelaHistoria4();
        telaHistoria4.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
        telaHistoria4.setVisible(true);
    }//GEN-LAST:event_botao1ActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        TelaInventario telaInventario = new TelaInventario();
        telaInventario.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
        telaInventario.setVisible(true);
    }//GEN-LAST:event_btnInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHistoria3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHistoria3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHistoria3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHistoria3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHistoria3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao1;
    private javax.swing.JButton btnInventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtHistoria;
    // End of variables declaration//GEN-END:variables
}
